import type { CareState, CareLearnResource } from "./types";

export const DEMO_PATIENT_ID = "patient_rajamma";
export const DEMO_DATE = "2026-09-04T10:42:00+05:30";

/** CareLearn starter packs for the Razorpay Buildathon demo. */
export const careLearnResources: CareLearnResource[] = [
  {
    id: "carelearn_wandering_001",
    title: "Wandering safety for the care circle",
    query: "calm response when an elder seems lost near home",
    role: ["caregiver", "neighbour", "rwa", "asha"],
    use_case: "wandering",
    language: ["English", "Hindi", "Kannada"],
    ndli_search_url: "",
    summary: "Gemini CareLearn pack: safe, calm community response when someone may be lost.",
    generated_training_card: "",
    quiz_questions: [],
    source_type: "carelearn"
  },
  {
    id: "carelearn_communication_001",
    title: "Calm communication with elders",
    query: "speak slowly one choice at a time dementia care",
    role: ["caregiver", "neighbour", "volunteer", "rwa"],
    use_case: "communication",
    language: ["English", "Hindi", "Kannada"],
    ndli_search_url: "",
    summary: "Speak slowly, keep choices simple, avoid arguing, and preserve dignity.",
    generated_training_card: "",
    quiz_questions: [],
    source_type: "carelearn"
  },
  {
    id: "carelearn_medication_001",
    title: "Medication routine support",
    query: "older adult medication adherence caregiver India",
    role: ["caregiver", "pharmacy", "asha"],
    use_case: "medication",
    language: ["English", "Hindi"],
    ndli_search_url: "",
    summary: "Refill reminders, safe escalation, and caregiver confirmation — no dosing advice.",
    generated_training_card: "",
    quiz_questions: [],
    source_type: "carelearn"
  },
  {
    id: "carelearn_stress_001",
    title: "Caregiver stress and rest",
    query: "caregiver stress support asking for help",
    role: ["caregiver", "asha", "doctor"],
    use_case: "caregiver_stress",
    language: ["English", "Hindi", "Kannada"],
    ndli_search_url: "",
    summary: "Burnout signals, rest planning, and how the care circle can share load.",
    generated_training_card: "",
    quiz_questions: [],
    source_type: "carelearn"
  },
  {
    id: "carelearn_community_001",
    title: "RWA and volunteer emergency response",
    query: "apartment community elderly emergency response India",
    role: ["asha", "rwa", "volunteer", "neighbour"],
    use_case: "emergency",
    language: ["English", "Hindi", "Kannada"],
    ndli_search_url: "",
    summary: "Local awareness pack for RWA, ASHA workers, and student volunteers.",
    generated_training_card: "",
    quiz_questions: [],
    source_type: "carelearn"
  }
];

/** @deprecated Use careLearnResources — kept for state field compatibility. */
export const ndliResources = careLearnResources;

export const seedState: CareState = {
  mode: "demo",
  demoStep: 0,
  patients: [
    {
      id: DEMO_PATIENT_ID,
      name: "Rajamma",
      age: 72,
      condition_stage: "mild dementia",
      primary_language: "Kannada",
      home_location: "Apartment near MSRIT, Mathikere",
      safe_zone_radius: 500,
      emergency_contacts: ["Ananya", "Lakshmi"],
      doctor_name: "Dr. Nair",
      medical_notes: "Mild dementia. No diagnosis is generated by RememberMe.",
      medication_schedule: ["Morning medicine after breakfast", "Evening medicine after dinner"],
      privacy_settings: ["Consent-aware face embeddings", "Unknown faces ignored", "Raw media expires unless saved"]
    }
  ],
  caregivers: [
    {
      id: "caregiver_ananya",
      patient_id: DEMO_PATIENT_ID,
      name: "Ananya",
      relation: "daughter",
      phone: "+91 demo",
      email: "ananya@example.com",
      notification_preferences: ["watch", "dashboard", "care circle"]
    }
  ],
  people: [
    {
      id: "person_ananya",
      patient_id: DEMO_PATIENT_ID,
      name: "Ananya",
      relation: "daughter",
      role: "family",
      trust_level: "primary",
      profile_photo_url: "/samples/ananya.svg",
      memory_note: "Visits every evening and talks about family and food.",
      allowed_visibility: "caregiver_only",
      last_seen_at: "2026-09-03T18:20:00+05:30",
      last_seen_location: "Home",
      last_conversation_summary: "Ananya reminded Rajamma that she would visit again on Friday evening.",
      consent_status: "consented"
    },
    {
      id: "person_lakshmi",
      patient_id: DEMO_PATIENT_ID,
      name: "Lakshmi",
      relation: "neighbour from downstairs",
      role: "neighbour",
      trust_level: "trusted",
      profile_photo_url: "/samples/lakshmi.svg",
      memory_note: "Often reminds Rajamma about lunch and medicine.",
      allowed_visibility: "care_circle",
      last_seen_at: "2026-09-03T10:35:00+05:30",
      last_seen_location: "Ramaiah temple gate",
      last_conversation_summary: "Lakshmi reminded Rajamma to eat lunch before taking medicine.",
      consent_status: "consented"
    },
    {
      id: "person_meena",
      patient_id: DEMO_PATIENT_ID,
      name: "Meena",
      relation: "ASHA worker",
      role: "asha",
      trust_level: "community",
      profile_photo_url: "/samples/meena.svg",
      memory_note: "Monthly health visit worker.",
      allowed_visibility: "care_circle",
      last_seen_at: "2026-09-02T09:00:00+05:30",
      last_seen_location: "Home",
      last_conversation_summary: "Meena checked caregiver notes and asked about sleep.",
      consent_status: "consented"
    },
    {
      id: "person_ravi",
      patient_id: DEMO_PATIENT_ID,
      name: "Ravi",
      relation: "pharmacy owner",
      role: "pharmacy",
      trust_level: "community",
      profile_photo_url: "/samples/ravi.svg",
      memory_note: "Delivers monthly medicines.",
      allowed_visibility: "care_circle",
      last_seen_at: "2026-09-02T17:15:00+05:30",
      last_seen_location: "Local pharmacy",
      last_conversation_summary: "Ravi confirmed the monthly refill date.",
      consent_status: "consented"
    },
    {
      id: "person_rwa",
      patient_id: DEMO_PATIENT_ID,
      name: "RWA Volunteer",
      relation: "apartment emergency volunteer",
      role: "rwa",
      trust_level: "emergency_only",
      profile_photo_url: "/samples/rwa.svg",
      memory_note: "Helps only when caregiver is unreachable.",
      allowed_visibility: "emergency",
      last_seen_at: "2026-09-01T12:00:00+05:30",
      last_seen_location: "Apartment lobby",
      last_conversation_summary: "RWA volunteer attended the care circle briefing.",
      consent_status: "consented"
    }
  ],
  places: [
    {
      id: "place_home",
      patient_id: DEMO_PATIENT_ID,
      name: "Home",
      type: "home",
      location: "Apartment near MSRIT",
      latitude: 13.0306,
      longitude: 77.565,
      risk_radius_m: 500,
      safety_level: "safe",
      notes: "Primary safe zone.",
      last_visit_at: "2026-09-04T08:15:00+05:30",
      usual_companions: ["Ananya"]
    },
    {
      id: "place_temple",
      patient_id: DEMO_PATIENT_ID,
      name: "Ramaiah temple gate",
      type: "temple",
      location: "Mathikere",
      latitude: 13.0321,
      longitude: 77.5664,
      risk_radius_m: 120,
      safety_level: "safe",
      notes: "Rajamma feels calm here.",
      last_visit_at: "2026-09-03T10:35:00+05:30",
      usual_companions: ["Lakshmi"]
    },
    {
      id: "place_pharmacy",
      patient_id: DEMO_PATIENT_ID,
      name: "Local pharmacy",
      type: "pharmacy",
      location: "MSRIT road",
      latitude: 13.0288,
      longitude: 77.5634,
      risk_radius_m: 120,
      safety_level: "safe",
      notes: "Ravi can call Ananya before dispensing.",
      last_visit_at: "2026-09-02T17:15:00+05:30",
      usual_companions: ["Ravi"]
    },
    {
      id: "place_road",
      patient_id: DEMO_PATIENT_ID,
      name: "Busy main road",
      type: "traffic_junction",
      location: "MSRIT gate",
      latitude: 13.0319,
      longitude: 77.5701,
      risk_radius_m: 180,
      safety_level: "risky",
      notes: "Avoid crossing alone.",
      last_visit_at: "2026-09-01T11:42:00+05:30",
      usual_companions: []
    }
  ],
  memoryEvents: [
    {
      id: "event_med_0815",
      patient_id: DEMO_PATIENT_ID,
      event_type: "medication_taken",
      timestamp: "2026-09-04T08:15:00+05:30",
      source: "caregiver",
      location: "Home",
      people_involved: ["Ananya"],
      summary: "Morning medicine marked taken after breakfast.",
      risk_score: 5,
      privacy_level: "caregiver_only",
      retention_policy: "7_days",
      action_items: ["Continue routine check after breakfast."]
    },
    {
      id: "event_orientation",
      patient_id: DEMO_PATIENT_ID,
      event_type: "orientation_check",
      timestamp: "2026-09-04T08:25:00+05:30",
      source: "voice",
      location: "Home",
      people_involved: ["Rajamma"],
      summary: "Morning orientation: 2 out of 3. Slightly below usual, no diagnosis.",
      risk_score: 18,
      privacy_level: "caregiver_only",
      retention_policy: "7_days",
      action_items: ["Low-priority note for caregiver."]
    },
    {
      id: "event_lakshmi_old",
      patient_id: DEMO_PATIENT_ID,
      event_type: "conversation",
      timestamp: "2026-09-03T10:42:00+05:30",
      source: "voice",
      location: "Ramaiah temple gate",
      people_involved: ["Lakshmi"],
      summary: "Lakshmi reminded Rajamma to eat lunch before taking medicine.",
      raw_transcript: "Did you eat lunch? Please take your medicine after food.",
      risk_score: 6,
      privacy_level: "care_circle",
      retention_policy: "saved",
      action_items: ["Check if medicine was taken."]
    },
    {
      id: "event_journal_mysore",
      patient_id: DEMO_PATIENT_ID,
      event_type: "memory_journal",
      timestamp: "2026-09-04T09:10:00+05:30",
      source: "voice",
      location: "Home",
      people_involved: ["Rajamma"],
      summary: "Rajamma remembered a happy trip to Mysore with her husband.",
      raw_transcript: "I remember going to Mysore with my husband.",
      risk_score: 2,
      privacy_level: "caregiver_only",
      retention_policy: "saved",
      action_items: ["Ask about the Mysore trip and wedding saree."]
    }
  ],
  alerts: [],
  communityTasks: [],
  ndliResources,
  careLearnTrainings: [],
  doctorReports: [],
  captureSessions: [],
  captureMedia: [],
  latestLocation: {
    patient_id: DEMO_PATIENT_ID,
    latitude: 13.0306,
    longitude: 77.565,
    accuracy: 40,
    captured_at: "2026-09-04T10:42:00+05:30",
    source: "simulated"
  },
  latestHealthSnapshot: {
    id: "health_seed",
    patient_id: DEMO_PATIENT_ID,
    steps_today: 2840,
    distance_m: 1860,
    active_minutes: 32,
    latest_heart_rate_bpm: 78,
    resting_heart_rate_bpm: 72,
    sleep_minutes: 385,
    sleep_quality_label: "fair",
    calories: 1460,
    source: "mixed",
    mocked_fields: ["sleep_minutes", "sleep_quality_label", "resting_heart_rate_bpm", "calories"],
    captured_at: "2026-09-04T09:30:00+05:30"
  },
  latestWatchCue: {
    id: "watch_cue_seed",
    patient_id: DEMO_PATIENT_ID,
    cue: "Good morning Rajamma. Today is Friday. Ananya will visit this evening. Let us start slowly.",
    source_event: "routine",
    created_at: "2026-09-04T08:20:00+05:30",
    should_vibrate: false,
    speak_mode: "speech_synthesis"
  },
  wearEvents: [],
  rewardPoints: 300,
  rewardTransactions: [
    {
      id: "reward_seed",
      patient_id: DEMO_PATIENT_ID,
      points: 300,
      reason: "Starter points for CareLearn onboarding.",
      source: "demo",
      created_at: "2026-09-04T09:00:00+05:30"
    }
  ],
  careBadges: [
    {
      id: "badge_welcome",
      title: "Care circle joined",
      description: "Opened RememberMe CareGrid for Rajamma's care network.",
      earned_at: "2026-09-04T09:00:00+05:30"
    }
  ],
  careStreakDays: 1,
  lastCareActivityAt: "2026-09-04T09:00:00+05:30"
};
